name: Dotnet Publish
description: Create the packeged output for a .NET Core project.

branding:
  color: purple
  icon: package

inputs:
  path:
    description: Path to the project to publish.
    required: false
    default: .
  output-dir:
    description: Directory where all packages will be put (default value is 'packages').
    required: false
    default: packages
  build-configuration:
    description: Build configuration for the build (default value is 'Release').
    required: false
    default: Release
  skip-build:
    description: Whether to skip the build using the --no-build flag (default value is 'true').
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Create Nuget packages
      shell: bash
      run: |
        ARGS=""
        if [[ '${{ inputs.skip-build }}' == "true" ]] ; then
          ARGS="${ARGS} --no-build"
        fi
        dotnet publish '${{ inputs.project-name }}' -o '${{ inputs.output-dir }}' -c '${{ inputs.build-configuration }}' ${ARGS}
